// Short descriptions and search keywords for every nav page. Shown on the mega-menu cards, the floating dock's fan-out, and used by the nav
// search ("find a page or function"). Keys are NavItem.key from navData.ts; a page without an entry here still works, it just has no blurb.
export const NAV_META: Record<string, { desc: string; kw?: string }> = {
  home: { desc: 'Your day at a glance: exceptions, orders, tasks and shortcuts', kw: 'start landing overview dashboard bento' },
  dashboard: { desc: 'Inventory health and days of supply across the company', kw: 'inventory health dos' },
  'on-hand': { desc: 'Current on hand, usage and days of supply by shop and product', kw: 'stock quantities usage' },
  monthend: { desc: 'Month-end counts, recounts, balances and outliers', kw: 'count recount ending balance outlier' },
  weekly: { desc: 'Weekly count schedule and results', kw: 'count weekly' },
  orders: { desc: 'The original order generator and history', kw: 'order generate legacy' },
  'orders-v2': { desc: 'Build, review and place suggested orders by vendor', kw: 'order generate reladyne valvoline po purchase suggest' },
  'po-status': { desc: 'Open, late and received purchase orders from Droptop', kw: 'po purchase order delivery received late' },
  projects: { desc: 'Projects, tasks and end-of-day review', kw: 'project task eod' },
  config: { desc: 'Locations, vendors, parts, order config and mappings', kw: 'configuration settings product usage vendor parts' },
  'location-lookup': { desc: 'Everything about one shop: on hand, tanks, order config, exceptions', kw: 'shop store location detail' },
  'custom-shop-config': { desc: 'Per-shop custom pricing and package arrangements', kw: 'custom pricing quart fee' },
  'am-rd-lookup': { desc: 'Area manager and regional director rollup of shops', kw: 'am rd area manager director' },
  'tank-monitors': { desc: 'Tank monitor readings, offline monitors and low VMI', kw: 'tank vmi keep fill skybitz offline monitor' },
  'procurement-deck': { desc: 'The monthly procurement update deck, slide by slide', kw: 'deck slides rebate cogs vendor' },
  'count-sheet': { desc: 'A shop working sheet for counting every product', kw: 'count sheet places' },
  'inventory-alerts': { desc: 'Inventory problems that need attention', kw: 'alerts missing data' },
  'exception-reporting': { desc: 'Automated exceptions, triage and the late PO list', kw: 'exception triage zero on hand adjustment duplicate case late po' },
  'location-comms': { desc: 'Log of contacts with shops and area managers', kw: 'communication email contact log' },
  'tank-links': { desc: 'Share links for shop tank calculators', kw: 'tank calculator share link' },
  'tank-review': { desc: 'Review tank counts submitted by shops', kw: 'tank count review' },
  'customer-heatmap': { desc: 'Where customers come from, on a map', kw: 'map customers heat' },
  'droptop-orders': { desc: 'Droptop orders with revenue, packages and M5%', kw: 'sales orders m5 revenue packages' },
  'droptop-vehicles': { desc: 'Vehicles serviced, makes, models and VIN decode', kw: 'vin vehicle car' },
  'droptop-packages': { desc: 'Service packages sold', kw: 'package service' },
  'package-mapping': { desc: 'Classify packages as oil change or M5', kw: 'classification m5 oil change' },
  'pricing-audit': { desc: 'Check package and product pricing against the list', kw: 'price audit retail cost custom packages' },
  'product-sales-history': { desc: 'Sales by shop and period for chosen products', kw: 'product sales history' },
  'staffing-report': { desc: 'Labor hours, LHCE and manager performance', kw: 'staffing labor hours lhce schedule' },
  'data-connections': { desc: 'Scheduled syncs, backfills and data health', kw: 'sync droptop monday skybitz backfill health schedule connection' },
  mmr: { desc: 'RelaDyne monthly management report', kw: 'reladyne gallons rebate' },
  'global-config': { desc: 'Company-wide configuration', kw: 'global settings admin' },
  outlier: { desc: 'Outlier reports and comments', kw: 'outlier report' },
  'outlier-am': { desc: 'Area manager outlier items to review', kw: 'outlier area manager' },
  'outlier-leadership': { desc: 'Leadership overview of outliers', kw: 'outlier leadership' },
  grni: { desc: 'Goods received not invoiced for month end', kw: 'grni accrual finance' },
  'cogs-price-check': { desc: 'Re-cost back-dated vendor price changes', kw: 'cogs price rebate finance' },
  'marketing-planner': { desc: 'Campaign plans by shop and month', kw: 'campaign marketing plan' },
  'menu-board': { desc: 'Lobby and bay menu boards, links and pricing', kw: 'menu board price franchise' },
  calendar: { desc: 'Schedule, events and checklists', kw: 'schedule events' },
  tasks: { desc: 'Your tasks and due dates', kw: 'todo task' },
  issues: { desc: 'Track issues to resolution', kw: 'issue tracker' },
  meetings: { desc: 'Meeting notes and follow-ups', kw: 'meeting notes' },
  forms: { desc: 'Build forms and review submissions', kw: 'form survey submission' },
  locations: { desc: 'Quick access to shops by owner, market and manager', kw: 'shops directory' },
  'feature-requests': { desc: 'Ask for new features and track requests', kw: 'request idea suggestion' },
}

/** Section blurbs for the mega menu header / dock. */
export const SECTION_BLURB: Record<string, string> = {
  inventory: 'Counts, ordering, shops and exceptions',
  droptop: 'Sales, vehicles, packages and staffing from Droptop',
  'shop-tools': 'Tools shared with shops',
  wip: 'Pages still being shaped',
  reladyne: 'RelaDyne reporting',
  'global-config': 'Company-wide settings',
  operations: 'Outlier reporting and operations',
  finance: 'Month-end accruals and pricing checks',
  marketing: 'Campaigns and menu boards',
}
