-- Adds "Mighty" as a real inventory.vendors row (Orders v2 Phase 1,
-- 2026-09-21) — previously only RelaDyne/Valvoline existed. Mighty
-- vendor-manages most shops' ordering directly; this row exists so the
-- handful of shops needing a manual order can be tracked/exported the
-- same way any other vendor's orders are, even though Mighty orders are
-- generated by the separate mightyEngine.ts (no location_order_config
-- rows for this vendor — see that file's own header comment).
INSERT INTO inventory.vendors (company_id, vendor_code, name)
SELECT company_id, 'MIGHTY', 'Mighty'
FROM inventory.vendors
WHERE vendor_code = 'RELADYNE'
ON CONFLICT DO NOTHING;
