-- Phase 2 (auth_rls_initplan): wrap unwrapped auth.uid()/auth.jwt()/auth.role()
-- calls in platform schema policies as (select auth.*()) so Postgres evaluates
-- them once per query (an init-plan) instead of once per row. Mechanical only —
-- every USING/WITH CHECK expression is unchanged except for this wrapping, so
-- access is identical to before.

ALTER POLICY "Users can delete their company's attachments" ON platform.attachments USING ((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Users can insert attachments for their company" ON platform.attachments WITH CHECK ((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Users can read their company's attachments" ON platform.attachments USING ((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Authenticated users can create companies" ON platform.companies WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Admin/dev manage custom_columns" ON platform.custom_columns USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid()))))) WITH CHECK ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Company members read custom_columns" ON platform.custom_columns USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Company members read custom_values" ON platform.custom_values USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Company members write custom_values" ON platform.custom_values USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid()))))) WITH CHECK ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "admin_dev_manage_connections" ON platform.data_connections USING ((( SELECT user_profiles.role FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid()))) = ANY (ARRAY['developer'::text, 'administrator'::text])));
ALTER POLICY "authenticated_read_connections" ON platform.data_connections USING (((select auth.role()) = 'authenticated'::text));
ALTER POLICY "dept_admin_all" ON platform.departments USING ((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = departments.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))));
ALTER POLICY "dept_company_member_select" ON platform.departments USING ((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = departments.company_id) AND (p.deleted_at IS NULL)))));
ALTER POLICY "Developer role can read/write dev_config" ON platform.dev_config USING (((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))) AND (( SELECT user_profiles.role FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid()))) = 'developer'::text))) WITH CHECK (((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))) AND (( SELECT user_profiles.role FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid()))) = 'developer'::text)));
ALTER POLICY "eci_delete" ON platform.event_checklist_items USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "eci_insert" ON platform.event_checklist_items WITH CHECK ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "eci_select" ON platform.event_checklist_items USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "eci_update" ON platform.event_checklist_items USING ((company_id = ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))));
ALTER POLICY "Authenticated users can upload files" ON platform.feature_request_files WITH CHECK (((select auth.uid()) = uploaded_by));
ALTER POLICY "Files readable by request owner and admins" ON platform.feature_request_files USING ((((select auth.uid()) = uploaded_by) OR (EXISTS ( SELECT 1 FROM platform.feature_requests WHERE ((feature_requests.id = feature_request_files.request_id) AND (feature_requests.submitted_by = (select auth.uid()))))) OR (EXISTS ( SELECT 1 FROM platform.user_profiles WHERE ((user_profiles.id = (select auth.uid())) AND (user_profiles.role = ANY (ARRAY['administrator'::text, 'developer'::text, 'admin'::text])))))));
ALTER POLICY "Authenticated users can add notes" ON platform.feature_request_notes WITH CHECK (((select auth.uid()) = author_id));
ALTER POLICY "Notes readable by request owner and admins" ON platform.feature_request_notes USING (((EXISTS ( SELECT 1 FROM platform.feature_requests WHERE ((feature_requests.id = feature_request_notes.request_id) AND (feature_requests.submitted_by = (select auth.uid()))))) OR (EXISTS ( SELECT 1 FROM platform.user_profiles WHERE ((user_profiles.id = (select auth.uid())) AND (user_profiles.role = ANY (ARRAY['administrator'::text, 'developer'::text, 'admin'::text])))))));
ALTER POLICY "Users manage own pings" ON platform.feature_request_pings USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Admins manage all requests" ON platform.feature_requests USING ((EXISTS ( SELECT 1 FROM platform.user_profiles WHERE ((user_profiles.id = (select auth.uid())) AND (user_profiles.role = ANY (ARRAY['administrator'::text, 'developer'::text, 'admin'::text]))))));
ALTER POLICY "Users manage own requests" ON platform.feature_requests USING (((select auth.uid()) = submitted_by)) WITH CHECK (((select auth.uid()) = submitted_by));
ALTER POLICY "issues_delete" ON platform.issues USING (((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = issues.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))) OR (created_by = (select auth.uid())) OR ((department_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM platform.user_department_memberships m WHERE ((m.user_id = (select auth.uid())) AND (m.department_id = issues.department_id)))))));
ALTER POLICY "issues_insert" ON platform.issues WITH CHECK (((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE ((user_profiles.id = (select auth.uid())) AND (user_profiles.deleted_at IS NULL)))) AND ((department_id IS NULL) OR (EXISTS ( SELECT 1 FROM platform.user_department_memberships m WHERE ((m.user_id = (select auth.uid())) AND (m.department_id = issues.department_id)))) OR (EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = issues.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))))));
ALTER POLICY "issues_select" ON platform.issues USING (((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = issues.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))) OR (created_by = (select auth.uid())) OR ((department_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM platform.user_department_memberships m WHERE ((m.user_id = (select auth.uid())) AND (m.department_id = issues.department_id)))) AND (NOT (EXISTS ( SELECT 1 FROM platform.issue_department_exclusions e WHERE ((e.issue_id = issues.id) AND (e.user_id = (select auth.uid()))))))) OR ((cardinality(shared_department_ids) > 0) AND (EXISTS ( SELECT 1 FROM platform.user_department_memberships m WHERE ((m.user_id = (select auth.uid())) AND (m.department_id = ANY (issues.shared_department_ids)))))) OR ((visibility = 'specific_users'::text) AND (EXISTS ( SELECT 1 FROM platform.issue_shares s WHERE ((s.issue_id = issues.id) AND (s.user_id = (select auth.uid())))))) OR ((visibility = 'attendees'::text) AND (EXISTS ( SELECT 1 FROM platform.issue_participants ip WHERE ((ip.issue_id = issues.id) AND (ip.user_id = (select auth.uid()))))))));
ALTER POLICY "issues_update" ON platform.issues USING (((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = issues.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))) OR (created_by = (select auth.uid())) OR ((department_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM platform.user_department_memberships m WHERE ((m.user_id = (select auth.uid())) AND (m.department_id = issues.department_id))))))) WITH CHECK ((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE ((user_profiles.id = (select auth.uid())) AND (user_profiles.deleted_at IS NULL)))));
ALTER POLICY "Users access own outlook events" ON platform.outlook_events USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Users manage own subscriptions" ON platform.outlook_subscriptions USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "user scope" ON platform.schedule_events USING (((company_id IN ( SELECT user_profiles.company_id FROM platform.user_profiles WHERE (user_profiles.id = (select auth.uid())))) AND ((created_by IS NULL) OR (created_by = (select auth.uid())) OR ((select auth.uid()) = ANY (COALESCE(assigned_to, ARRAY[]::uuid[]))))));
ALTER POLICY "membership_admin_all" ON platform.user_department_memberships USING ((EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = user_department_memberships.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'administrator'::text, 'developer'::text])) AND (p.deleted_at IS NULL)))));
ALTER POLICY "membership_self_select" ON platform.user_department_memberships USING (((user_id = (select auth.uid())) OR (EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = user_department_memberships.company_id) AND (p.role = ANY (ARRAY['admin'::text, 'developer'::text])) AND (p.deleted_at IS NULL))))));
ALTER POLICY "Admins can update company users" ON platform.user_profiles USING (((company_id = get_my_company_id()) AND (( SELECT user_profiles_1.role FROM platform.user_profiles user_profiles_1 WHERE (user_profiles_1.id = (select auth.uid()))) = ANY (ARRAY['admin'::text, 'administrator'::text, 'developer'::text]))));
ALTER POLICY "Users can insert own profile" ON platform.user_profiles WITH CHECK ((id = (select auth.uid())));
ALTER POLICY "Users can update own profile" ON platform.user_profiles USING ((id = (select auth.uid())));
ALTER POLICY "Users can view own profile" ON platform.user_profiles USING ((id = (select auth.uid())));
ALTER POLICY "admins_update_company_profiles" ON platform.user_profiles USING ((((select auth.uid()) = id) OR (EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = user_profiles.company_id) AND (p.role = 'admin'::text)))))) WITH CHECK ((((select auth.uid()) = id) OR (EXISTS ( SELECT 1 FROM platform.user_profiles p WHERE ((p.id = (select auth.uid())) AND (p.company_id = user_profiles.company_id) AND (p.role = 'admin'::text))))));
